name: Publish package

on:
  release:
    types: [published, edited]

permissions: {}

jobs:
  build-and-publish-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
      - name: Publish package
        shell: bash
        # TODO: Switch to trusted publishing
        run: |  # zizmor: ignore[use-trusted-publishing]
          poetry config repositories.custom 'https://test.pypi.org/legacy/'
          poetry config pypi-token.custom ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish --build --no-interaction --repository custom
  build-and-publish:
    needs: build-and-publish-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
      - name: Publish package
        shell: bash
        # TODO: Switch to trusted publishing
        run: |  # zizmor: ignore[use-trusted-publishing]
          echo "Using default repository (PyPi)"
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction
